name: playground
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker: ^0.4.10
  path_provider: ^0.4.1
  test_platform_view:
    git: https://github.com/karmactonics/test_platform_view.git
  firebase_admob_platform_view:
    git: https://github.com/karmactonics/firebase_admob_platform_view.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/
